[package]
name = "smallweb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
urlencoding = "2.1.0"
async-std = {version = "1.11.0", features = ["attributes"]}
futures = "0.3"